name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.6.0

      - name: Test devbox
        run: devbox run -- echo "done!"

      - name: Build
        run: devbox run build

      - name: Generate
        run: devbox run generate

      - name: Validate
        # TODO(kakkoyun): Remove the exlusion of out directory once we have reproducible builds.
        run: git diff --exit-code ':!out/'
